name: pp5
channels:
  - conda-forge
  - schrodinger # pymol
  - sbl         # dssp
  - bioconda    # clustal, muscle, blast
  - r           # r-fraction
dependencies:
  # Basic
  - pip
  - python=3.11.*
  # Development
  # Project Dependencies
  - biopython
  - black
  - blast
  - clustalo
  - dask
  - sbl::dssp
  - filelock
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - more-itertools
  - muscle
  - nglview
  - nodejs
  - numba
  - numpy
  - pandas
  - pre-commit
  - pymol-bundle
  - vtk-m=1.5.1 # required due to issue with pymol, newer version causes failure
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pytest-repeat
  - pytest-xdist
  - requests
  - rpy2
  - scikit-learn
  - scipy
  - seaborn
  - toml
  - tqdm
  - uncertainties
  # r-dependencies (for torustest)
  - r-doparallel
  - r-fraction # (might require r channel)
  - r-ggplot2
  - r-pracma
  - r-proxy
  - r-transport
  # pip dependencies
  - pip:
    - nbmerge
    - -e .  # install this package
platforms:
  - linux-64
  - osx-64
