name: arpeggio
channels:
  - conda-forge
dependencies:
  # Base
  - pip
  - python=3.9.*
  # Deps for arpeggio
  # https://github.com/PDBeurope/arpeggio
  - biopython
  - gemmi
  - openbabel
  - pip:
    - pdbe-arpeggio
platforms:
  - linux-64
  - osx-64
